Important Formatting for a better overview
Humans-of-Julia/HoJBot.jl pull request #115
Opened 2021-08-07 18:44 UTC by Konrad570

Formatting is very important for an better Overview of the Code
Specially in some Code Editors and Screen sizes the Code is very hard to read and editable. This was a few good format to prevend any failure with spaces etc.

2021-08-09 06:55 UTC, Azzaare requested changes

2021-08-09 06:55 UTC, Azzaare commented on src/command/ig.jl
> +return df
This change is actually a mistake, `return` should be indented

2021-08-09 06:55 UTC, Azzaare commented on src/command/ig.jl
> +end
Here also is very odd

2021-08-09 06:55 UTC, Azzaare commented on src/command/jc.jl
> +    end
Here too

2021-08-09 06:58 UTC, Azzaare commented
Hi, thanks for the PR.

Even though we forgot to mention it in the README, we try to follow the following guidelines: https://github.com/invenia/BlueStyle

In your PR, many changes are great for visibility. Some other changes go against the abovementioned guideline. And a few also introduce bad indenting.
It is probably necessary to build upon this PR to make it converge to something adequate.

2021-08-09 12:25 UTC, Konrad570 commented
Okay I see, what about the other changes that aren’t odd, will you change this in the upcoming updates?

> Am 09.08.2021 um 08:58 schrieb Jean-Francois Baffier ***@***.***>:
> 
> ﻿
> Hi, thanks for the PR.
> 
> Even though we forgot to mention it in the README, we try to follow the following guidelines: https://github.com/invenia/BlueStyle
> 
> In your PR, many changes are great for visibility. Some other changes go against the abovementioned guideline. And a few also introduce bad indenting.
> It is probably necessary to build upon this PR to make it converge to something adequate.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-08-11 05:15 UTC, Azzaare commented
I have used an automated formatting tool set on Blue Style and made a PR based on your fork.
It is not perfect, but as you can see, some changes you made conflict with that style (and some don't).

As this is a collaborative project, it seems hard to move to another style without approval of most collaborators. If you feel that Blue Style is not satisfying for you, please let us know why and what are the critical parts are.

2021-09-04 20:02 UTC, tk3369 commented
Let's close this issue since the standard julia formatter from vscode is broken. See #118 for a new attempt.

2021-09-04 20:02 UTC, closed without merging